/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: '#4F5D3F',
        secondary: '#8C9F7B',
        accent: '#3E4F73',
        background: '#EFEBE0',
        surface: '#FCF9F4',
        'surface-alt': '#D2D4C7',
        'surface-chip': '#D8D3C6',
        text: '#2F2F2F',
        'text-secondary': '#6B6A62',
        'text-tertiary': '#9B9A91',
        'text-inverse': '#FFFFFF',
        'status-high': '#4F5D3F',
        'status-medium': '#C4943A',
        'status-low': '#A85C3A',
        'overlay-selected': 'rgba(255, 255, 255, 0.15)',
      },
      spacing: {
        4: '4px',
        8: '8px',
        12: '12px',
        16: '16px',
        20: '20px',
        24: '24px',
        32: '32px',
        40: '40px',
      },
      borderRadius: {
        'radius-sm': '8px',
        'radius-md': '16px',
      },
      boxShadow: {
        'shadow-map': '0 2px 8px rgba(47, 47, 47, 0.5)',
      },
      zIndex: {
        'z-overlay': '10',
        'z-dropdown': '20',
        'z-map-card': '30',
        'z-nav': '40',
        'z-modal': '50',
      },
      fontFamily: {
        lora: ['var(--font-lora)', 'serif'],
        'dm-sans': ['var(--font-dm-sans)', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'display-l': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'heading-xl': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'heading-l': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'heading-m': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'heading-s': ['16px', { lineHeight: '24px', fontWeight: '700' }],
        'heading-italic': ['24px', { lineHeight: '32px', fontWeight: '700', fontStyle: 'italic' }],
        'body-l': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-m': ['14px', { lineHeight: '24px', fontWeight: '400' }],
        'body-s': ['12px', { lineHeight: '20px', fontWeight: '400' }],
        'ui-button': ['16px', { lineHeight: '20px', fontWeight: '700' }],
        'ui-label-l': ['16px', { lineHeight: '20px', fontWeight: '700' }],
        'ui-label-m': ['12px', { lineHeight: '16px', fontWeight: '700' }],
        'ui-label-s': ['10px', { lineHeight: '14px', fontWeight: '700' }],
        'ui-caption': ['12px', { lineHeight: '20px', fontWeight: '400' }],
        'ui-overline': ['10px', { lineHeight: '14px', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
